package View;

import DataBase.Vectores;
import javax.swing.JOptionPane;
import DataBase.Logic;
import java.util.Arrays;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author nFelix457
 */
public class EasyGame extends javax.swing.JDialog {

    public ImageIcon imgs[];
    Logic logic = new Logic();
    Vectores vector = new Vectores();
    String variable = "";
    String firstPain = "";
    int intentosFallidos = 1;
    int contaIntentos = 0;
    char[] palabra = vector.getVectorCharString(vector.getEasyVector());
    char[] copiaPalabraConGuiones = new char[palabra.length];

    public EasyGame(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        
        //ELIMINAR ESTO, esta en rules esta parte comentada por si no entiende
        LlenarVector();
        intentosFallidos = 0;
        contaIntentos = 0;

        imgs = new ImageIcon[7];
        imgs[0] = new ImageIcon(getClass().getResource("/View/img/im1.jpg"));
        imgs[1] = new ImageIcon(getClass().getResource("/View/img/im2.jpg"));
        imgs[2] = new ImageIcon(getClass().getResource("/View/img/im3.jpg"));
        imgs[3] = new ImageIcon(getClass().getResource("/View/img/im4.jpg"));
        imgs[4] = new ImageIcon(getClass().getResource("/View/img/im5.jpg"));
        imgs[5] = new ImageIcon(getClass().getResource("/View/img/im6.jpg"));
        imgs[6] = new ImageIcon(getClass().getResource("/View/img/im7.jpg"));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_agregar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        salida = new javax.swing.JTextField();
        bt_back = new javax.swing.JButton();
        jl_attempts = new javax.swing.JLabel();
        counter = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ingresaLetra = new javax.swing.JTextPane();
        btn_Img = new javax.swing.JButton();
        volverInicio2 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        btn_agregar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btn_agregar.setText("Comprobar letra");
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel1.setText("Ingrese una letra");

        salida.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        salida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salidaActionPerformed(evt);
            }
        });

        bt_back.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        bt_back.setText("Regresar");
        bt_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_backActionPerformed(evt);
            }
        });

        jl_attempts.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jl_attempts.setText("Intentos ");

        counter.setEditable(false);
        counter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                counterActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(ingresaLetra);

        volverInicio2.setText("Volver Inicio");
        volverInicio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverInicio2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(salida, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_agregar)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)))
                .addGap(94, 94, 94)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jl_attempts, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(counter, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))
                    .addComponent(btn_Img, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE))
                .addGap(80, 80, 80))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(bt_back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(volverInicio2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_attempts)
                    .addComponent(counter, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(btn_Img, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btn_agregar)
                        .addGap(55, 55, 55)
                        .addComponent(salida, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_back, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(volverInicio2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
        //contiene el metodo logicaEasyGame que se encarga de la logica del juego
        //y el de si gana o pierde
        ganarOPerder(logic.siGano3(palabra, copiaPalabraConGuiones));
        variable = "";
        logicaEasyGame();
        ingresaLetra.setText("");
    }//GEN-LAST:event_btn_agregarActionPerformed

    private void salidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salidaActionPerformed

    private void bt_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_backActionPerformed
        // da un salto atras y nos devulve una ventana
        setVisible(false);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        Levels level = new Levels((JFrame) this.getParent(), true);
        level.setVisible(true);
    }//GEN-LAST:event_bt_backActionPerformed

    private void counterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_counterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_counterActionPerformed

    private void volverInicio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverInicio2ActionPerformed
        //nos lleva a la primer ventana de la app
        Start s = new Start();
        this.setVisible(false);
        s.setVisible(true);
    }//GEN-LAST:event_volverInicio2ActionPerformed

    //metodo encargado de validar mediante util.regex el ingreso de solo letras
    public boolean validacionRegex (String ingreso) {
        String prueba = ingreso;
        if (prueba.matches("[a-z]*")) {
            return true;
        } else {
            JOptionPane.showMessageDialog(this, "ERROR\n\nNo es una letra");
            return false;
        }
    }

    /*
    * encargado de la logica del juego, este metodo agrega la letra si es correcta o cuenta un error si es incorrecta
    * ademas de pintar en pantalla lo que se introduce o no
    
    */
    public void logicaEasyGame() {
        contaIntentos++;
        counter.setText("" + contaIntentos);
        if (validacionRegex(ingresaLetra.getText().toLowerCase()) == true) {
            for (int i = 0; i < copiaPalabraConGuiones.length; i++) {
                if (palabra[i] == ingresaLetra.getText().toLowerCase().charAt(0)) {
                    copiaPalabraConGuiones[i] = ingresaLetra.getText().toLowerCase().charAt(0);
                    variable += copiaPalabraConGuiones[i] + " ";
                } else {
                    variable += copiaPalabraConGuiones[i] + " ";
                }
            }

        }

        salida.setText(variable);

        //si lo que hace es que si la letra no esta en la palabra lo cuenta como intento fallido
        if (contadorIntentosFallidos() == false) {
            intentosFallidos++;
            btn_Img.setIcon(imgs[intentosFallidos]);
        }
        ganarOPerder(logic.siGano3(palabra, copiaPalabraConGuiones));
    }

    public void Inicio() {
        btn_Img.setIcon(imgs[0]);
        btn_Img.getIcon();
    }

    public boolean contadorIntentosFallidos() {
        for (int i = 0; i < copiaPalabraConGuiones.length; i++) {
            if (copiaPalabraConGuiones[i] == ingresaLetra.getText().toLowerCase().charAt(0)) {
                return true;
            }
        }
        return false;
    }

    public void LlenarVector() {
        for (int i = 0; i < copiaPalabraConGuiones.length; i++) {
            copiaPalabraConGuiones[i] = '_';
            firstPain += copiaPalabraConGuiones[i] + " ";
        }
        salida.setText(firstPain);
    }

    public void ganarOPerder(boolean siGano) {
        //junto a si gano dice si alguien gana o pierde
        if (Arrays.equals(palabra, copiaPalabraConGuiones) || intentosFallidos == 6) {
            if (siGano == true) {
                JOptionPane.showMessageDialog(this, "Felicidades usted ha ganado");
                setVisible(false);
                setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                Levels level = new Levels((JFrame) this.getParent(), true);
                level.setVisible(true);

            } else if (siGano == false || intentosFallidos == 6) {
                JOptionPane.showMessageDialog(this, "Has perdido");

                setVisible(false);
                setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                Levels level = new Levels((JFrame) this.getParent(), true);
                level.setVisible(true);

            }
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_back;
    private javax.swing.JButton btn_Img;
    private javax.swing.JButton btn_agregar;
    private javax.swing.JTextField counter;
    private javax.swing.JTextPane ingresaLetra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jl_attempts;
    private javax.swing.JTextField salida;
    private javax.swing.JToggleButton volverInicio2;
    // End of variables declaration//GEN-END:variables
}
