/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import FileManagerBinary.ReaderManager;
import static Main.Main.personList;
import Model.Person;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *class that contains the operation and the graphical interface of the user login screen
 * @author Felix Navarro,Leonardo Gómez,Marcell Granados,Jimmy Avila
 * @version 18-11-2019
 */
public class EnterKay extends javax.swing.JFrame {

    /**
     * Creates new form EnterKay
     * @param parent
     * @param modal
     */
    public EnterKay(java.awt.Frame parent, boolean modal) {
        initComponents();
        setLocationRelativeTo(parent);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbIngreso = new javax.swing.JLabel();
        lbUserName = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        lbPassword = new javax.swing.JLabel();
        btAcept = new javax.swing.JButton();
        btReturn = new javax.swing.JButton();
        txtPassWord = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        lbIngreso.setFont(new java.awt.Font("Caladea", 3, 24)); // NOI18N
        lbIngreso.setForeground(new java.awt.Color(0, 51, 153));
        lbIngreso.setText("Ingreso de Usuario");

        lbUserName.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbUserName.setForeground(new java.awt.Color(0, 51, 153));
        lbUserName.setText("Nombre de Usuario:");

        lbPassword.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbPassword.setForeground(new java.awt.Color(0, 51, 153));
        lbPassword.setText("Contraseña:");

        btAcept.setText("Aceptar");
        btAcept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAceptActionPerformed(evt);
            }
        });

        btReturn.setText("Volver");
        btReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btReturnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(lbIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 127, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addComponent(lbUserName)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btAcept, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(230, 230, 230))
            .addGroup(layout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addComponent(lbPassword)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtUserName, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                    .addComponent(txtPassWord))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lbIngreso)
                .addGap(28, 28, 28)
                .addComponent(lbUserName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPassWord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(btAcept, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAceptActionPerformed

        ReaderManager reader = new ReaderManager();
        char [] passWord = txtPassWord.getPassword();
        String pass = new String(passWord);
        String userName = txtUserName.getSelectedText();
        Person p = new Person(userName, pass);
        

        try {
            reader.open("Person.bin");
            personList = reader.read();
            reader.close();
            System.out.println("Lectura exitosa");

        } catch (IOException e) {
            System.err.println("error de archivo");
            System.err.println(e.getMessage());

        } catch (ClassNotFoundException e) {
            System.err.println("error de archivo");
            System.err.println(e.getMessage());

        }

        int account = 0;
        for (int i = 0; i < personList.getPersonCounter(); i++) {
            if (txtUserName.getText().equals(personList.getPerson(i).getUserName())
                && txtPassWord.getText().equals(personList.getPerson(i).getPassWord())) {
                personList.setPerson2(i);
                account++;
                i = personList.getPersonCounter();
                
            } 
        }

            if (account >= 1) {
                
               
                Rules rules = new Rules(null, true);
                setVisible(false);
                rules.setVisible(true);
                

            } else {
                JOptionPane.showMessageDialog(null, "Este usuario NO existe, por favor ingresar un usuario para Jugar");
            }

    }//GEN-LAST:event_btAceptActionPerformed

    private void btReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btReturnActionPerformed
        Start start = new Start();
        setVisible(false);
        start.setVisible(true);
    }//GEN-LAST:event_btReturnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAcept;
    private javax.swing.JButton btReturn;
    private javax.swing.JLabel lbIngreso;
    private javax.swing.JLabel lbPassword;
    private javax.swing.JLabel lbUserName;
    private javax.swing.JPasswordField txtPassWord;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
