/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DataBase.Logic;
import java.util.Arrays;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;

/**
 *
 * @author Felix Navarro
 */
public class Help extends javax.swing.JDialog {

    public ImageIcon imgs[];
    Logic logic = new Logic();
    
    char[] palabra = new char[8];
    char[] palabraMala = new char[8];
    char[] copia = new char[palabra.length];
    char[] copiaMala = new char[palabra.length];
    int varDeJugarMal = 0;
    int varDeJugarBien = 0;
    int contMal = 0;
    String imprimir = "";

    /**
     * Creates new form Help
     */
    public Help(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setSize(700, 600);

        //llena el vector apenas se incia la ventana de help
        LlenarVector(copia);

        //llena el vector con la palabra calentar
        palabra[0] = 'c';
        palabra[1] = 'a';
        palabra[2] = 'l';
        palabra[3] = 'e';
        palabra[4] = 'n';
        palabra[5] = 't';
        palabra[6] = 'a';
        palabra[7] = 'r';

        //se crea un vector con letras aleatorias y del mismo tamaño que el vector de la palabra obtenida
        palabraMala[0] = 'x';
        palabraMala[1] = 'z';
        palabraMala[2] = 'w';
        palabraMala[3] = 'k';
        palabraMala[4] = 'p';
        palabraMala[5] = 'm';
        palabraMala[6] = 'v';
        palabraMala[7] = 't';

        //se crea un vector de imagenes que provienen de la ruta de acceso /View/img/im1.jpg
        imgs = new ImageIcon[7];
        imgs[0] = new ImageIcon(getClass().getResource("/View/img/im1.jpg"));
        imgs[1] = new ImageIcon(getClass().getResource("/View/img/im2.jpg"));
        imgs[2] = new ImageIcon(getClass().getResource("/View/img/im3.jpg"));
        imgs[3] = new ImageIcon(getClass().getResource("/View/img/im4.jpg"));
        imgs[4] = new ImageIcon(getClass().getResource("/View/img/im5.jpg"));
        imgs[5] = new ImageIcon(getClass().getResource("/View/img/im6.jpg"));
        imgs[6] = new ImageIcon(getClass().getResource("/View/img/im7.jpg"));

        //pinta al inicio la imagen cero del vector anterior de imagenes
        btn_Img.setIcon(imgs[0]);
    }
    String firstPain = "";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt_back = new javax.swing.JButton();
        bt_repeat = new javax.swing.JButton();
        btn_Img = new javax.swing.JButton();
        salida = new javax.swing.JTextField();
        btn_Siguiente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        salida2 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        bt_back.setText("Salir");
        bt_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_backActionPerformed(evt);
            }
        });

        bt_repeat.setText("Repetir");
        bt_repeat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_repeatActionPerformed(evt);
            }
        });

        salida.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        salida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salidaActionPerformed(evt);
            }
        });

        btn_Siguiente.setText("Siguiente");
        btn_Siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SiguienteActionPerformed(evt);
            }
        });

        salida2.setColumns(20);
        salida2.setRows(5);
        jScrollPane1.setViewportView(salida2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(bt_back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 453, Short.MAX_VALUE)
                .addComponent(bt_repeat)
                .addGap(84, 84, 84))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(salida, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(btn_Siguiente))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Img, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Img, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(salida, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btn_Siguiente)
                        .addGap(53, 53, 53)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_back)
                    .addComponent(bt_repeat))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_backActionPerformed
        // boton que retorna a la ventana anterior
        Rules rule = new Rules(null, true);
        setVisible(false);
        rule.setVisible(true);
    }//GEN-LAST:event_bt_backActionPerformed

    // el vector se llena de guiones bajos para luego ser remplazados por letras
    public void LlenarVector(char[] copia) {
        for (int i = 0; i < copia.length; i++) {
            copia[i] = '_';
            firstPain += copia[i] + " ";
        }
        salida.setText(firstPain);
    }

    //nos enseña a jugar correctamente
    public boolean JugarCorrectamente() {
        //si la funcion de jugar correctamente esta completa entonces muestra un mensaje y retorna un true que el boton de siguiente lo interpretara
        //como un paso a la forma de jugar mal
        if (Arrays.equals(copia, palabra)) {
            if (varDeJugarMal == 0) {
                JOptionPane.showMessageDialog(this, "Asi se debe de jugar\n para ver como no se debe de jugar precione siguiente");
                varDeJugarMal = varDeJugarMal + 1;
            }
            return true;
        } else {
            copia[varDeJugarBien] = palabra[varDeJugarBien];

            salida2.setText("La palabra es calentar\n\nla letra ingresada fue: " + palabra[varDeJugarBien]);
            salida.setText(imprimir);
            varDeJugarBien = varDeJugarBien + 1;

            for (int i = 0; i < copia.length; i++) {
                imprimir += copia[i] + " ";
            }
            return false;
        }
    }

    public void jugarIncorrectamente() {
        LlenarVector(copiaMala);
        copiaMala[contMal] = palabraMala[contMal];
        btn_Img.setIcon(imgs[contMal]);

        for (int j = 0; j < copiaMala.length; j++) {
            imprimir += " _ ";
        }

        salida2.setText("La palabra es calentar\n\nla letra ingresada fue: " + palabraMala[contMal]);
        salida.setText(imprimir);
        contMal++;
        if (contMal == copiaMala.length - 1) {
            JOptionPane.showMessageDialog(this, "Asi es como no se debe de jugar");

            if (btn_Siguiente.isSelected()) {
                imprimir = "";
            }
        }
    }


    private void salidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salidaActionPerformed
        // nos devuelve a la vetana de niveles
        setVisible(false);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        Levels level = new Levels((JFrame) this.getParent(), true);
        level.setVisible(true);
    }//GEN-LAST:event_salidaActionPerformed

    private void btn_SiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SiguienteActionPerformed
        //controla la forma correcta y incorrecta de jugar en ese orden
        imprimir = "";
        if (JugarCorrectamente() == true) {
            jugarIncorrectamente();
        } else {
            btn_Img.setIcon(imgs[0]);
            JugarCorrectamente();
            varDeJugarBien = varDeJugarBien - 1;
        }
    }//GEN-LAST:event_btn_SiguienteActionPerformed

    private void bt_repeatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_repeatActionPerformed
        // reinicia todo para que boton siguiente vuelva a comenzar de cero
        salida.setText("");
        varDeJugarBien = 0;
        varDeJugarMal = 0;
        imprimir = "";
        contMal = 0;
        LlenarVector(copia);
        LlenarVector(copiaMala);
        btn_Siguiente.isSelected();
        btn_Img.setIcon(imgs[0]);
        salida.setText("");
    }//GEN-LAST:event_bt_repeatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_back;
    private javax.swing.JButton bt_repeat;
    private javax.swing.JButton btn_Img;
    private javax.swing.JButton btn_Siguiente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField salida;
    private javax.swing.JTextArea salida2;
    // End of variables declaration//GEN-END:variables
}
