/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DataBase.Vectores;
import DataBase.Logic;
import java.util.Arrays;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Felix Navarro
 */
public class MediumGame extends javax.swing.JDialog {
public ImageIcon imgs[];
    /**
     * Creates new form StartGame
     */
    public MediumGame(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.setSize(776, 470);
        LlenarVector();
            //ESTE ES PARA VER CUANTAS VECES FALLA ALGUIEN, SI LLEGA A 6 EN EL METODO DE LLAMARRECURSIVIDAD SE INICIA Y FINALIZA LA PARTIDA
        intentos = 0;
        cont = 0;
        contaIntentos = 0;
        
                imgs = new ImageIcon[7];
        imgs[0] = new ImageIcon(getClass().getResource("/View/img/im1.jpg"));
        imgs[1] = new ImageIcon(getClass().getResource("/View/img/im2.jpg"));
        imgs[2] = new ImageIcon(getClass().getResource("/View/img/im3.jpg"));
        imgs[3] = new ImageIcon(getClass().getResource("/View/img/im4.jpg"));
        imgs[4] = new ImageIcon(getClass().getResource("/View/img/im5.jpg"));
        imgs[5] = new ImageIcon(getClass().getResource("/View/img/im6.jpg"));
        imgs[6] = new ImageIcon(getClass().getResource("/View/img/im7.jpg"));
        
    }
    int  contaIntentos = 0;
    Logic logic = new Logic();
    Vectores vector = new Vectores();
    String var = "";
    int cont = 0;
    String firstPain = "";
    int intentos = 0;
    char[] vectorLlegada = vector.getVectorCharString(vector.getMediumVector());
    char[] letrasConGuiones = new char[vectorLlegada.length];

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_attempts = new javax.swing.JLabel();
        bt_back = new javax.swing.JButton();
        counter = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ingresaLetra = new javax.swing.JTextPane();
        btn_agregar = new javax.swing.JButton();
        salida = new javax.swing.JTextField();
        btn_Img = new javax.swing.JButton();
        volverInicio2 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jl_attempts.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jl_attempts.setText("Intentos ");

        bt_back.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        bt_back.setText("Regresar");
        bt_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_backActionPerformed(evt);
            }
        });

        counter.setEditable(false);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel1.setText("Ingrese una letra");

        jScrollPane2.setViewportView(ingresaLetra);

        btn_agregar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btn_agregar.setText("Comprobar letra");
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });

        salida.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        salida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salidaActionPerformed(evt);
            }
        });

        volverInicio2.setText("Volver Inicio");
        volverInicio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverInicio2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bt_back)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(volverInicio2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 377, Short.MAX_VALUE)
                                .addComponent(jl_attempts)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(counter, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_agregar)
                                    .addComponent(salida, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(96, 96, 96)
                                .addComponent(btn_Img, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)))))
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(counter, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_attempts, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_agregar)
                        .addGap(47, 47, 47)
                        .addComponent(salida, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_Img, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bt_back)
                        .addGap(17, 17, 17))
                    .addComponent(volverInicio2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_backActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        Levels level = new Levels((JFrame) this.getParent(), true);
        level.setVisible(true);
    }//GEN-LAST:event_bt_backActionPerformed

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
        // TODO add your handling code here:
        //ALERTA
        //CUANDO VAYAMOS A REINICIAR LA PARTIDA HAY QUE FORMATEAR EL CONTADOR
        LlamadaRecursivo(logic.siGano3(vectorLlegada, letrasConGuiones));
        cont++;
        var = "";
        revisar();
        ingresaLetra.setText("");
    }//GEN-LAST:event_btn_agregarActionPerformed

    public boolean regexxx(String ingreso) {
        String prueba = ingreso;
        if (prueba.matches("[a-z]*")) {
            return true;
        } else {
            JOptionPane.showMessageDialog(this, "ERROR\n\nNo es una letra");
            return false;
        }
    }

    public void revisar() {
       // prueba.setIcon(imgs[0]);
       contaIntentos++;
       counter.setText("" + contaIntentos);
        if (regexxx(ingresaLetra.getText().toLowerCase()) == true) {
            for (int i = 0; i < letrasConGuiones.length; i++) {
                if (vectorLlegada[i] == ingresaLetra.getText().toLowerCase().charAt(0)) {
                    letrasConGuiones[i] = ingresaLetra.getText().toLowerCase().charAt(0);
                    var += letrasConGuiones[i] + " ";
                } else {
                    var += letrasConGuiones[i] + " ";
                }
            }
            
        }
        
        salida.setText(var);
        
        if (contador() == false) {
            intentos++;
            btn_Img.setIcon(imgs[intentos]);
        }
        LlamadaRecursivo(logic.siGano3(vectorLlegada, letrasConGuiones));
    }
    
    public void Inicio(){
    btn_Img.setIcon(imgs[0]);
    btn_Img.getIcon();
    }

    public boolean contador() {
        for (int i = 0; i < letrasConGuiones.length; i++) {
            if (letrasConGuiones[i] == ingresaLetra.getText().toLowerCase().charAt(0)) {
                return true;
            }
        }
        return false;
    }

    public void LlenarVector() {
        for (int i = 0; i < letrasConGuiones.length; i++) {
            letrasConGuiones[i] = '_';
            firstPain += letrasConGuiones[i] + " ";
        }
        salida.setText(firstPain);
    }

    public void LlamadaRecursivo(boolean siGano) {
         //un if  de este que haga la validacion de un contador de vidas para el ahorcado de juam diego
        //   || lo de juandiego
        if (Arrays.equals(vectorLlegada, letrasConGuiones) || intentos == 6) {
            if (siGano == true) {
                JOptionPane.showMessageDialog(this, "Felicidades usted ha ganado");
                    setVisible(false);
                    setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                    Levels level = new Levels((JFrame) this.getParent(), true);
                    level.setVisible(true);

            } else if (siGano == false || intentos == 6) {
                JOptionPane.showMessageDialog(this, "Has perdido");

                    setVisible(false);
                    setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                    Levels level = new Levels((JFrame) this.getParent(), true);
                    level.setVisible(true);

            }
        }
    }
    private void salidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salidaActionPerformed

    private void volverInicio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverInicio2ActionPerformed
        Start s = new Start();
        this.setVisible(false);
        s.setVisible(true);
    }//GEN-LAST:event_volverInicio2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_back;
    private javax.swing.JButton btn_Img;
    private javax.swing.JButton btn_agregar;
    private javax.swing.JTextField counter;
    private javax.swing.JTextPane ingresaLetra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jl_attempts;
    private javax.swing.JTextField salida;
    private javax.swing.JToggleButton volverInicio2;
    // End of variables declaration//GEN-END:variables
}
