package View;

import FileManagerBinary.WriterManager;
import Model.Person;
import static Main.Main.personList;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 * class that contains the operation and the graphical interface of the user registration screen
 * @author Felix Navarro,Leonardo Gómez,Marcell Granados, Jimmy Avila
 * @version 18-11-2019
 */
public class Register extends javax.swing.JFrame {

    private Person person;

    /**
     * 
     * @param parent
     * @param modal
     */
    public Register(java.awt.Frame parent, boolean modal) {
        initComponents();
        setLocationRelativeTo(parent);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbUserName = new javax.swing.JLabel();
        lbPassword = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        btAcept = new javax.swing.JButton();
        btCancel = new javax.swing.JButton();
        txtPassWord = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLabel1.setFont(new java.awt.Font("Caladea", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Inscribirse como Jugador");

        lbUserName.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbUserName.setForeground(new java.awt.Color(0, 0, 153));
        lbUserName.setText("Nombre de Usuario:");

        lbPassword.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbPassword.setForeground(new java.awt.Color(0, 51, 153));
        lbPassword.setText("Contraseña:");

        btAcept.setText("Aceptar");
        btAcept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAceptActionPerformed(evt);
            }
        });

        btCancel.setText("Cancel");
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtPassWord, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                                .addComponent(txtUserName, javax.swing.GroupLayout.Alignment.TRAILING))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(btAcept, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 209, Short.MAX_VALUE)
                        .addComponent(btCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(107, 107, 107))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(lbUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lbUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbPassword)
                .addGap(18, 18, 18)
                .addComponent(txtPassWord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAcept, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
       dispose();
    }//GEN-LAST:event_btCancelActionPerformed

    private void btAceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAceptActionPerformed
        Start start = new Start();
        WriterManager writer = new WriterManager();
        char []passWord = txtPassWord.getPassword();
        String pass = new String(passWord);
        String userName = txtUserName.getText();
        int counter=0;
        
      
        if(userName.length() >= 4 && pass.length() >= 3&&userName.length() <= 8 && pass.length() <=10){
            Person usuario = new Person(userName,pass);
        
        // If para saber si es la primera persona que agrega al vector
        if(personList.getPersonCounter()==0){
            personList.addPerson(usuario);
        }else{
            for (int i = 0; i < personList.getPersonCounter(); i++) {  
                System.out.println("entro");
                //If que valida si el nombre es igual
                if (userName.equals(personList.getPersonList()[i].getUserName())) {
                    JOptionPane.showMessageDialog(null, "Este usuario ya existe, proceda a ingresar, gracias");
                    //Si ya existe este nombre, el contador se suma
                    counter++;
                }
            }
            // Si el contador es mayor a 0(porque el nombre introducido era igual a un nombre ya registrado), no agregara a ningun usuario, 
            // Si el contador sigue siendo 0 (osea que el nombre introducido no es igual a ningun nombre registrado) el usuario se agregara
            if(counter == 0){
                personList.addPerson(usuario);
            }
        }
        
        try {
            writer.open("Person.bin");
            writer.write();
            writer.close();
            System.out.println("Ingresado en el archivo");
        } catch (IOException e) {
            System.err.println("Error en el archivo");
            System.err.println(e.getMessage());
        }
           dispose();
           
        }else if (userName.length() < 4 && pass.length() < 3) {
                JOptionPane.showMessageDialog(null, "Error, su nombre es de " + userName.length() + " caracteres y debe ser igual o mayor a 4, su contraseña es de " + pass.length() + " caracteres y debe ser igual o mayor a 3");

            } else if (pass.length() < 3) {
                JOptionPane.showMessageDialog(null, "Error, su contraseña es de " + pass.length() + " caracteres y debe ser igual o mayor a 3");

            } else if (userName.length() < 4) {
                JOptionPane.showMessageDialog(null, "Error, su nombre es de " + userName.length() + " caracteres y debe ser igual o mayor a 4");

            } else if (userName.length() > 8 && pass.length() > 10) {
                JOptionPane.showMessageDialog(null, "Error, su nombre es de " + userName.length() + " caracteres y debe ser igual o menor a 8, su contraseña es de " + pass.length() + " caracteres y debe ser igual o menor a 10");

            } else if (userName.length() > 8) {
                JOptionPane.showMessageDialog(null, "Error, su nombre es de " + userName.length() + " caracteres y debe ser igual o menor a 8");

            } else if (pass.length() > 10) {
                JOptionPane.showMessageDialog(null, "Error, su contraseña es de " + pass.length() + " caracteres y debe ser igual o menor a 10");
            }
        
    }//GEN-LAST:event_btAceptActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAcept;
    private javax.swing.JButton btCancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbPassword;
    private javax.swing.JLabel lbUserName;
    private javax.swing.JPasswordField txtPassWord;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
